services:
  - type: web
    name: youtube-downloader
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /