services:
  - type: web
    name: youtube-downloader
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /